### ISSUE TITLE
Cannot login through the Connect plugin on http site

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#832] opened 2024-03-22 13:08 UTC
Currently it's impossible to login through insecure context. When trying to login the `window.crypto.subtle` object is undefined: 
![image](https://github.com/hawtio/hawtio-next/assets/46345469/9de07187-a371-4318-a2c8-4d791682fc92)

Either hawtio should not work in insecure context at all (which is IMO the worse option) or hawtio should also work in insecure context. 

Note: `localhost` or `127.0.0.1` is considered safe by the browser so the subtle object is present, but when even on the PC's IP such as  `http://192.168.0.143:3000/hawtio/` the website is considered insecure and the object is missing. And there's no note about it, the button just doesn't do anything for the user.

**Comment by tadayosi** [comment] 2024-03-25 09:19
The Connect plugin's capability to connect to a remote JVM with BASIC authentication is now supported only when Hawtio is running on `localhost` or secured with HTTPS. This requirement is due to the limitation that Web Crypt API is only available in secure contexts:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

What we can do is to provide the user better UI feedback when they are trying to use the Connect plugin over BASIC authentication in an insecure way, which might lead to compromise the credentials over an insecure channel and thus is not supported.

**Comment by tadayosi** [comment] 2024-03-26 06:10
FYI, the issue is caused by support for secure session storage at #760.

**Comment by grgrzybek** [comment] 2024-04-29 15:08
Somehow, even on http://localhost, browser can add the `Authorization` header to jolokia proxy requests after displaying browser's native popup (to get `Basic` credentials).

I've created #910 because I was able to broke something and I have to dig deeper.

**Comment by mmuzikar** [comment] 2024-04-30 06:59
http://localhost is considered secure for development purposes (i guess :D) but http://<ip address> (other than 127.0.0.1) isn't.

**Comment by grgrzybek** [comment] 2024-05-06 12:29
Some test scenarios I found:

**Connect after clearing "HTTP authentications"**

* run `yarn start` in top level dir of hawtio-next
* start remote Jolokia application with `-javaagent:jolokia-agent-jvm-2.0.2-javaagent.jar=port=7778,protocol=http,debug=true,discoveryEnabled=true,user=grgr,password=grgr`
* import this connection:
```json
[
  {
    "name": "grgr-test-jolokia",
    "scheme": "http",
    "host": "localhost",
    "port": 7778,
    "path": "/jolokia"
  }
]
```
* CTRL-SHIFT-DEL in Firefox (or similar in Chrome) to clear _active logins_:
![image](https://github.com/hawtio/hawtio-next/assets/306565/02888c52-b306-4af8-a92c-17c7771c7a77)
* click "Connect" - new window/tab opens with URL like http://localhost:3000/hawtio/?con=name and native browser popup:
![image](https://github.com/hawtio/hawtio-next/assets/306565/e61ec091-99ef-4d79-b0e2-9842b3897f61)
* when you enter invalid credentials, these are immediately tried by the browser - you can't see it in network tab, but you can see the packet in Wireshark. Native dialog is redisplayed.
* when you click "cancel", `/hawtio/proxy/http/localhost/...` requests end with 401 and Hawtio displays React dialog to enter the credentials
   * hitting cancel closes the tab
   * hitting close (x) closes the tab
   * entering wrong credentials displays "Incorrect username or password" - 401 request is visible in Wireshark
   * entering correct credentials refreshes the page, adds `connect.salt` and `connect.credentials` to session storage and additionally browser offers to store the credentials in its own storage. only one entry in password manager is created:
![image](https://github.com/hawtio/hawtio-next/assets/306565/85537cc0-1edc-4795-8faf-1cc4cf2f33da)
   * if we then close the tab and click "Connect" again from main Hawtio and if we didn't store the credentials in browser itself, native credentials popup is displayed again
   * but I checked that after saving credentials in the browser, we still see native dialog when clicking "Connect" again...
* if you'd type valid credentials, no React dialog would be shown and Firefox would offer to store the credentials. Nothing is stored in session storage.
![image](https://github.com/hawtio/hawtio-next/assets/306565/3f0e46b7-71c7-4b79-9c4a-f34dcb5f1763)
   * if you save the credentials in browser, next time you click "Connect", no native or React dialog is shown. Two entries in password manager are stored:
![image](https://github.com/hawtio/hawtio-next/assets/306565/81d5d48c-889e-4bb2-94c3-32b65ee14a3b)

**Clearing "HTTP authentications" when connected tab is working**

(session storage should not contain encrypted credentials, so we should use the path that doesn't involve React dialog from Hawtio.)

* Connected agent's tab is opened and we can see successful `/proxy` requests
* After clearing HTTP authentications we can see native dialog during next tick for proxy request
* closing the dialog without entering credentials - page is refreshed and native dialog is displayed again
* another close - we can see React dialog
* When entering bad credentials, dialog is redisplayed
* When entering correct credentials, browser offers to save them in password manager

**Comment by tadayosi** [comment] 2024-05-07 08:29
@grgrzybek Thanks for your detailed report. However, at this moment, it appears to me a different issue than the original one, as the original issue doesn't get involved with the browser native prompt. Maybe it's better to discuss it further with a separate issue, as it may require a different fix.

**Comment by grgrzybek** [comment] 2024-05-08 14:22
For the record, when using `/proxy` endpoint, we're doing same-origin requests and:
* with `xhr` we can't decide about sending `Authorization` header and [`withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) option is ignored:
> Setting withCredentials has no effect on same-origin requests
* with `fetch` API, we can use [`credetntials`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) option to decide about sending the credentials

With XHR (used by Jolokia) every time an attempt is made and we didn't specify the credentials in browser-native popup, the popup will be redisplayed. Once the credentials are entered, the popup won't show until we clear "Active logins".

With fetch API, if we'd use explicit `credentials: 'omit'` we could test for 401 and display React dialog to enter the credentials. BTW - this is exactly what happens if we explicitly close the native popup when connecting to remote Jolokia where `/proxy` returns proxied 401.

**Comment by grgrzybek** [comment] 2024-05-10 12:36
When checking connections on http and my ip address different than 127.0.0.1 I see some weird issues with hanged connection.
Seems like hawtioMiddleware returns `CanceledError: Request stream has been aborted` sometimes and then I can see Jolokia agent hanged waiting for some data on JDK HTTP incoming requests... Checking.

**Comment by tadayosi** [comment] 2024-05-13 05:05
> When checking connections on http and my ip address different than 127.0.0.1

If the connection is authenticated, you cannot use http with a hostname/ip address other than localhost/127.0.0.1.

**Comment by grgrzybek** [comment] 2024-05-13 05:51
When connecting directly to Jolokia agent with Basic auth enabled, both invocations work:
```
curl -u grgr:grgr 'http://localhost:7778/jolokia/' -X POST -H 'Accept: text/json' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'Content-Length: 18' -d '{"type":"version"}'

curl -u grgr:grgr 'http://localhost:7778/jolokia/' -X POST -H 'Accept: application/json' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'Content-Length: 18' -d '{"type":"version"}'
```

When connecting via hawtioMiddleware proxy, this works:
```
curl -u grgr:grgr 'http://localhost:3000/hawtio/proxy/http/localhost/7778/jolokia/' -X POST -H 'Content-Type: text/json' -H 'Content-Length: 18' -d '{"type":"version"}'
```
it's visible in Wireshark:
![image](https://github.com/hawtio/hawtio-next/assets/306565/d5ce8ed4-4422-46ff-84c3-8dfbb1de51c1)


but this fails:
```
curl -u grgr:grgr 'http://localhost:3000/hawtio/proxy/http/localhost/7778/jolokia/' -X POST -H 'Content-Type: application/json' -H 'Content-Length: 18' -d '{"type":"version"}'
```

now backend communication in Wireshark:
![image](https://github.com/hawtio/hawtio-next/assets/306565/b942d26f-7252-412b-9c06-ae63ea493869)

The error is:
```
error proxying to "http://localhost:7778/jolokia/: CanceledError: Request stream has been aborted
```

@tadayosi I know it's again a bit off topic, but maybe there's something wrong with hawtioMiddleware - I'm not yet that familiar with webpack's server + axios client.

**Comment by grgrzybek** [comment] 2024-05-13 09:01
I can display this warning. WDYT @tadayosi @mmuzikar ?
![image](https://github.com/hawtio/hawtio-next/assets/306565/ab33415d-9fbe-4b1c-8ebb-8a0c4ffb2fe9)

**Comment by grgrzybek** [comment] 2024-05-15 13:02
I'll at some point add a documentation section about "Connect" plugin (dedicated (sub)chapter?), but here's a little summary:

* for http://localhost, http://127.0.0.1 and https://anything everything works as before
* for http://not-localhost (see https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) there's some change - by we CAN'T connect to remote Jolokia agents if these require authentication and the icon is yellow (warning).

For non-secure browsing contexts there's a warning on the connect page:
![image](https://github.com/hawtio/hawtio-next/assets/306565/027b8983-22a1-46a1-99c4-b1a2aee3dfae)

List of configured connections may display yellow icons and the "Connect" button is disabled:
![image](https://github.com/hawtio/hawtio-next/assets/306565/d4962f6f-e48b-45ff-9dd5-7da06d5441b1)

And finally when editing a connection to secured Jolokia in non-secure browsing context, we can see the error:
![image](https://github.com/hawtio/hawtio-next/assets/306565/812c53fa-93f6-4745-acbc-45df79e3b20c)

There are also some enhancements in secure contexts

we display some more details when testing connection:
![image](https://github.com/hawtio/hawtio-next/assets/306565/33fdac6d-4459-43dc-986e-6f61881c243c)

we display current connection after connecting to remote agent:
![image](https://github.com/hawtio/hawtio-next/assets/306565/2728633f-e343-426e-91eb-2b7ff14ee7d5)

**Closed** 2024-05-15 13:07 UTC
Labels: kind/enhancement, area/connect, kind/ux
