### ISSUE TITLE
[Bug] Camel Route Debug - breakpoint doesn't hold a route

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#535] opened 2023-09-05 15:27 UTC
Hello @tadayosi 

I have found unusual behaviour of Camel Route Debug when a breakpoint is added.

My understanding is the following - when the breakpoint is added, the exchange is on hold on the node where the breakpoint was set and you have two options - either click on Step (next) or click on Resume to continue the exchange.

However, when I tried to add the breakpoint, I see that the numbers (see the attached screenshot) are still counting and as I understand the exchange is not on hold and continues anyway.

<img width="1242" alt="Screenshot 2023-09-05 at 18 17 37" src="https://github.com/hawtio/hawtio-next/assets/49488040/a0ad516b-b5d1-4e81-8453-1c2bfd7725c6">

Is it expected behaviour or it's a bug?

Thank you

**Comment by phantomjinx** [comment] 2023-09-05 17:10
I have seen this a few times and assumed it was exchanges 'catching up'. I did do some 'debugging' (ha!) on it a while back and found it goes all the way down to the camel route in that the JMX flags are all properly set but things seem to keep going.

**Comment by tadayosi** [comment] 2024-06-10 00:40
@mmelko Could you take a look at it along with your PF 5 upgrade work?

**Comment by mmelko** [comment] 2024-10-21 16:26
@tadayosi don't think this is related to PF5 at all. I've tested also on old hawtio 2.18 and the behaviour is practically the same. Although we do have some regression happening here.

**Comment by tadayosi** [comment] 2024-10-22 04:19
@mmelko I see it's not related to PF5. I was asking it because you're the author of the Debug feature 🙂
If you can explain to Juri why it's the expected behaviour then we can close it.

**Comment by mmelko** [comment] 2024-10-22 13:10
@tadayosi no it was done by @phantomjinx . 
@jsolovjo if I understand correctly the excange actually is on hold, but the number of exchanges looks suspicious. When I click on step I can see the numbers sort of correctly: 
this is your state: 
![Image](https://github.com/user-attachments/assets/5b329f55-d93f-4cc3-a7a9-27cd14bb3e04)
however on the next steps: 
![Image](https://github.com/user-attachments/assets/8d8bbf03-8c05-48b7-91e4-a1edd08b2c98)
![Image](https://github.com/user-attachments/assets/201429d8-1f24-4467-a146-455f9b665f94)


I will double check the stats.

**Closed** 2024-10-23 08:07 UTC
Labels: kind/bug, help wanted, area/camel
