### ISSUE TITLE
Operations - Expanded view of operation is reset every once in a while

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#363] opened 2023-06-19 14:47 UTC
Noticed this while testing the other tickets after rebasing. The operations view gets reset every few in a while.  Has a similar solution to #273 so I'll be including the fix there
![Peek 2023-06-19 16-51](https://github.com/hawtio/hawtio-next/assets/17336236/e5fdc06f-7aab-4086-80a6-b101e5dc8241)

**Comment by tadayosi** [comment] 2023-06-20 04:59
Duplicate of #346. This should be already fixed with #360.

**Closed by tadayosi** 2023-06-20 04:59 UTC
