### ISSUE TITLE
E2E - Run the E2E suite from Hawtio standalone project directly with hawtio-next

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#322] opened 2023-06-07 02:14 UTC
As the E2E tests are growing in the downstream Hawtio standalone project, there is now a noticeable time lag before changes applied to the UI in hawtio-next could be seen to affect the downstream E2E tests. Currently, before changes made in hawtio-next can be validated by the downstream E2E tests, a new NPM package for hawtio-next must first be released and then a fix must be committed that applies it on the Hawtio standalone project side.

This time lag is not desirable, and ideally, as soon as a pull request is submitted that changes UI on hawtio-next, those downstream E2E tests should be used to validate it before it is merged.

One possible idea to resolve this situation is to clone a snapshot of the `3.x` branch from the Hawtio standalone repository in the GitHub CI workflow here and directly run it with the latest hawtio-next by using `yarn link` with it.

**Comment by tadayosi** [comment] 2023-06-07 02:15
@jsolovjo What do you think about this?

**Comment by tadayosi** [comment] 2023-06-07 02:23
Even in this case, there still remain some issues.

If the E2E tests could be executed here, then how should we fix it if any of them actually fails? The tests are downstream, so in any case, you would need to commit the fix and apply it downstream before fixing the tests. You may have to put the tests in a state where it continues to fail temporarily.

**Comment by jsolovjo** [comment] 2023-06-07 08:45
@tadayosi you have raised very important questions here.

In ideal world, if the tests fail then something wrong with the committed code. However, as the hawtio-next is still under development, I understand that there might be new and/or refactored features which will cause app's logic/behaviour change and require test refactoring - it's also very true.

I have one idea - not sure how good it is

Create a new workflow
Use some image like ubuntu
Define steps, for instance, using bash to pull hawtio and run SB/Quarkus app with Camel integrations
Have e2e test features in hawtio-next, define an extra `before` step to connect to the running app, run the e2e tests

Wha do you think?

**Comment by jsolovjo** [comment] 2023-06-07 09:12
Another suggestion is from Matej
```
so I woudln't pull the hawtio code .. I'd use that in the git that's why I'd use hawtio-next project. The easiest would be to have already some camel-quarkus with jmx prebuilt and pushed in quay for example
so you would just pull that docker image and run the hawtio and tests directly in github action
```

**Comment by jsolovjo** [comment] 2023-06-07 15:50
@tadayosi 
What if we will create a several images containing SB and Quarkus apps with Camel integrations and Sample Plugin using jdk11 and jdk17, and pushing them into quay, then add or migrate test features and helpers into hawtio-next project, then create a github workflow which will pull and run the images, then run the tests from hawtio-next with one extra `before` step as connect to the app?

As an example I have created this image `quay.io/fuse_qe/hawtio-springboot-jdk11:latest` which is a SB app with simple Camel integration and Sample plugin using jdk11. 

@mmuzikar mentioned it's not a problem to automate the proccess of pushing new images intp quay once there are new changes in hawtio project, so quay images will be up-to-date.

**Comment by jsolovjo** [comment] 2023-06-07 16:14
Or another idea:

what if to create a kind of listener, once there is a PR in hawtio-next, then run e2e tests in hawtio project but pulling hawtio-next with a development tag. Not sure how to implement it as I am not expert in github actions and not sure how hawtio is designed to use it

**Comment by tadayosi** [comment] 2023-06-08 08:03
> what if to create a kind of listener, once there is a PR in hawtio-next, then run e2e tests in hawtio project but pulling hawtio-next with a development tag. Not sure how to implement it as I am not expert in github actions and not sure how hawtio is designed to use it

I think it's important to have a workflow in the hawtio-next project, as it would be then easily integrated with the checking of pull reqs here. If we have it in the hawtio standalone project, I'm not sure if we could integrate it with pull reqs submitted here for checking.

**Comment by tadayosi** [comment] 2023-06-08 08:15
Building some docker image for Camel apps under test is also great idea. But what I'd like to consider here is not only reuse of sample applications but also reuse of Hawtio Java build and test features themselves. It is important that we should be able to have a Hawtio Java build which includes hawtio-next with the pull req changes applied.

**Comment by mmuzikar** [comment] 2023-06-08 08:56
I'm getting lost in all the proposals and requirements so I'll try to summarize / ask questions to narrow us down some path:
 - We somehow need to link hawtio-next to hawtio and run the e2e tests on it
 - What would be the "best" state for the system under test? - Can it be just the camel app with hawtio but we can start hawtio-next and connect to the app? Or would it be safer to have the hawtio-next ui already running in the system under test?
 - Will this e2e test run be required to merge any PRs or will it be more informative because downstream and hawtio-next aren't in sync
 
For docker images I think it would be possible to produce both SUT images and a test image that we could point to an address to execute the tests on.

And considering failing tests, we could take functionality from our other testsuites where if a scenario fails and is annotated with a github issue then it can be considered skipped.

**Comment by jsolovjo** [comment] 2023-06-08 09:17
@mmuzikar actually, test features are the same for both quarkus and spring boot runtimes, so we have another branch where we are refactoring and putting them into one `features` module. So we will have `tests/quarkus`, `tests/springboot` and `tests/features`. The work is still in progress.

I believe the idea is to run those tests on every `hawtio-next` PR to decrease feedback time. We have already faced the issues when new changes were merged into `hawtio-next`, then we run E2E tests on `hawtio` and they fail.

@tadayosi 
If we have a docker image, for instance, java app with camel and we have rewritten features in `hawtio-next`. Then we start tests on `hawtio-next` branch from PR and tell it to connect to the running app - it should use a new version of UI, right?

**Comment by tadayosi** [comment] 2023-06-09 05:11
> If we have a docker image, for instance, java app with camel and we have rewritten features in hawtio-next. Then we start tests on hawtio-next branch from PR and tell it to connect to the running app - it should use a new version of UI, right?

@jsolovjo Right. And this sounds like a nice approach. The only concern with this is that we need to duplicate the feature definitions between hawtio-next and hawtio standalone projects. If we duplicate them, we'd need to maintain the same set of test features in two different places and keep them in sync. Or, if we can divide them into 1) tests that are purely UI oriented and non-related to runtimes, and 2) tests that should involve runtimes such as login, authentication, and smoke tests, then we can remove the duplicate and maintain them separately.

Thinking it a bit further, probably we can use Cucumber.js + Cypress #190 for implementing E2E tests here. Do you have any other different thoughts? @jsolovjo @mmuzikar

**Comment by mmuzikar** [comment] 2023-06-09 07:01
What about containerizing the tests as well? This way we could just do a docker run in hawtio-next and have the test logic same for both projects

**Comment by tadayosi** [comment] 2023-06-09 08:39
> What about containerizing the tests as well? This way we could just do a docker run in hawtio-next and have the test logic same for both projects

@mmuzikar If it's possible, that sounds like a great idea. I wonder how it can be achieved. Is it something like switching the test target endpoint for the containerised tests to localhost:3000 on the github workflow for hawtio-next?

**Comment by jsolovjo** [comment] 2023-06-09 08:56
I think it's possible and for instance, we could have 2 images - app and tests, and then run tests on hawtio-next connecting to the images so feedback time will be quick. And there wouldn't be an issue to fix something we will need just to update one image which contains test features and push it.

**Comment by mmuzikar** [comment] 2023-06-09 08:57
> I wonder how it can be achieved. Is it something like switching the test target endpoint for the containerised tests to localhost:3000 on the github workflow for hawtio-next?

Yes exactly, and to keep the same functionality as we have in hawtio right now if an endpoint is not specified the testsuite would just start a docker container with a specified runtime and use that.

> Another concern with this approach would be that we still need to go a long distance when we actually find some test failures, on which we should then fix the test scenarios at the hawtio standalone project.
Agreed. However I expect this will have more informational character - as in if tests fail because of a hawtio regression then the PR should be changed. If tests are failing because the UI changed we could figure out a way to ignore the test failures if a github issue was raised to fix those tests.
Or another thing that comes to mind that would help would be the ability to specify a specific branch of the `hawtio` project to use the tests from (it'd be a bit more complex but on the other hand would be a good feedback for both the test and the UI that the tests pass)

**Comment by tadayosi** [comment] 2023-06-12 05:32
> Agreed. However I expect this will have more informational character - as in if tests fail because of a hawtio regression then the PR should be changed. If tests are failing because the UI changed we could figure out a way to ignore the test failures if a github issue was raised to fix those tests.

Totally makes sense. Fully agreed.

> Or another thing that comes to mind that would help would be the ability to specify a specific branch of the hawtio project to use the tests from (it'd be a bit more complex but on the other hand would be a good feedback for both the test and the UI that the tests pass)

Sounds like promising idea, but maybe a bit too much as the initial step. Let's revisit it after we implement the initial workflow and still see room for improvement.

**Comment by tadayosi** [comment] 2023-06-12 05:50
@jsolovjo @mmuzikar

> What about containerizing the tests as well? This way we could just do a docker run in hawtio-next and have the test logic same for both projects

So, I think this idea of Martin's is worth working on as the initial step. To do so, what we need to do would be:

1. Containerise the two test suites:
    - [tests/springboot](https://github.com/hawtio/hawtio/tree/3.x/tests/springboot)
    - [tests/quarkus](https://github.com/hawtio/hawtio/tree/3.x/tests/quarkus)
2. Create and containerise a shared Camel application with Jolokia endpoint attached that can showcase every hawtio-next feature in [the hawtio standalone project](https://github.com/hawtio/hawtio)
    - I think this should be a Quarkus application
3. Define an E2E workflow that utilises the two containers at hawtio-next

Do you think you can work on it?

One thing we need to be careful is that the authentication feature which may be utilised from the e2e tests isn't available at hawtio-next, as it doesn't have a real backend runtime that provides authentication. So we'd need to either make it possible for the e2e tests to run partially that are relevant for hawtio-next, or [implement a mock at hawtio-next](https://github.com/hawtio/hawtio-next/blob/main/app/craco.config.js#L100-L146) so that the full e2e tests can run at hawtio-next (while I'm not sure if it's possible at this moment).

**Comment by tadayosi** [comment] 2023-07-31 07:31
I think it's done with #457 thanks to @mmuzikar. Can we close this issue?

**Closed** 2023-08-07 07:24 UTC
Labels: area/test, kind/discussion, area/ci
