### ISSUE TITLE
Operation dropdowns can't be opened

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#325] opened 2023-06-07 08:58 UTC
In JMX operations the dropdowns on the righthand side don't open when clicked on. Curiously it is possible to open when clicking and pressing enter at the same time.
![Peek 2023-06-07 10-51](https://github.com/hawtio/hawtio-next/assets/46345469/8274ac49-e451-4e0b-9a89-068fe91ecdb3)

I did a little investigation into the code and found out that `handleDropdownToggle` is called twice in [OperationForm.tsx](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/shared/operations/OperationForm.tsx#L52)
From patternfly docs I noticed that the callback can accept a boolean param, but setting the isDropdownOpen to that param also does nothing as the callback is still called twice (once with `true` and then with `false`)

When digging deeper into the KebabToggle it appears that it reacts to the click event on the toggle and then immediately new click event is handled for a non-existing element which it assumes is click somewhere else in the document so it closes the dropdown immediately.

I don't really understand why that's happening in hawtio when it's following the example code from here https://www.patternfly.org/v4/components/dropdown

**Comment by tadayosi** [comment] 2023-06-07 09:13
Thanks. Actually, I think it's a duplicate of #273. Let me close it in favour of the predecessor. Thanks for your investigation, too.

**Closed by tadayosi** 2023-06-07 09:13 UTC
Labels: kind/bug, area/jmx

**Comment by joshiraez** [comment] 2023-06-19 15:11
To add a little more info, the problem was that the component was being refreshed all the time. That would reset the state every time you clicked the button, so it went from true, refresh, back directly to false.
